import os

SECRET_KEY = os.getenv("SUPERSET_SECRET_KEY", "change-this-in-production")
FEATURE_FLAGS = {
    "DASHBOARD_NATIVE_FILTERS": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
}
TALISMAN_ENABLED = False
WTF_CSRF_ENABLED = False
SQLLAB_CTAS_NO_LIMIT = True
SUPERSET_WEBSERVER_TIMEOUT = 120
